# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
